### ISSUE TITLE
some mpi tests fail

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/ansible-role-fleur#4]
When enabling MPI, some (but not all) tests of the MPI executable fail:
* see [travis](https://travis-ci.org/marvel-nccr/ansible-role-fleur/builds/438093136#L494)
* see [extracted test log](https://github.com/marvel-nccr/ansible-role-fleur/files/2453371/mpi-travis.txt)
* see [output](https://github.com/marvel-nccr/ansible-role-fleur/files/2453400/out.txt) of failed test 48

```
    The following tests FAILED:
             28 - FLEUR_MPI:CuBulk (Failed)
             29 - FLEUR_MPI:CuBulkXML (Failed)
             32 - FLEUR_MPI:Fe-Atom (Failed)
             37 - FLEUR_MPI:Fe_bct (Failed)
             38 - FLEUR_MPI:Fe_bctXML (Failed)
             39 - FLEUR_MPI:PTO (Failed)
             40 - FLEUR_MPI:PTOXML (Failed)
             43 - FLEUR_MPI:PTO-SOC (Failed)
             46 - FLEUR_MPI:Fe_bct_SOCXML (Failed)
             48 - FLEUR_MPI:SiFilmSlicePlotXML (Failed)
```

**Comment by broeder-j** [comment]
Is this still and issue? I think for the current release this is not a problem, since still the full fast test set is run. So this can be closed I think. The fleur MPI test required the right environment variables to be set. Could have been a compiler related thing, back then problems with gfortran only were slowly fixed. From this output it is not reconstructable.

**Comment by ltalirz** [comment]
i think the tests weren't actually run on travis anymore, but I've now switched them back on in #11 
Looks like they run through fine (base on "Test failed." not found in the outputs).
A direct check e.g. on the quantum mobile VM might still be useful.
